name: Update Version on PR Merge

on:
  pull_request:
    types: [closed]  # Trigger this workflow when a PR is closed (merged or just closed)

permissions:
  contents: write
  pull-requests: read  # Only read access is needed to fetch PR labels

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure the full history is fetched

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'  # Adjust to your .NET version

    - name: Get PR Labels
      id: get_labels
      run: |
        if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
          echo "PR not merged. Exiting."
          exit 0
        fi
        
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Fetching labels for PR #${PR_NUMBER}"
        
        # Fetch PR labels using GitHub API
        labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels" \
                          | jq -r '.[].name')
        
        echo "Labels: $labels"

        # Determine increment type based on labels
        if echo "$labels" | grep -q 'major'; then
          echo "INCREMENT=major" >> $GITHUB_ENV
        elif echo "$labels" | grep -q 'minor'; then
          echo "INCREMENT=minor" >> $GITHUB_ENV
        else
          echo "INCREMENT=patch" >> $GITHUB_ENV
        fi

    - name: Increment version
      id: increment_version
      run: |
        file="ConsoleApp1CICD/Properties/AssemblyInfo.cs" # Update path to reflect your project structure

        # Extract current version
        version=$(grep -oP '(?<=\[assembly: AssemblyVersion\(")[^"]+' $file)
        echo "Current version: $version"

        # Extract major, minor, patch, and revision
        IFS='.' read -r major minor patch revision <<< "$version"

        # Determine increment based on environment variable
        case $INCREMENT in
          major)
            major=$((major + 1))
            minor=0
            patch=0
            revision=0
            ;;
          minor)
            minor=$((minor + 1))
            patch=0
            revision=0
            ;;
          patch)
            patch=$((patch + 1))
            ;;
          *)
            echo "Invalid increment type: $INCREMENT"
            exit 1
            ;;
        esac

        new_version="$major.$minor.$patch.$revision"
        echo "New version: $new_version"

        # Replace the version in AssemblyInfo.cs using a pipe delimiter
        sed -i "s|\[assembly: AssemblyVersion(\"$version\")\]|\[assembly: AssemblyVersion(\"$new_version\")\]|g" $file
        sed -i "s|\[assembly: AssemblyFileVersion(\"$version\")\]|\[assembly: AssemblyFileVersion(\"$new_version\")\]|g" $file

        # Debug: Print the file content after modification
        echo "Modified file content:"
        cat $file

        # Output the new version so it can be used in later steps
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "ahtesham-haq"
        git config user.email "ahtesham.ul.haq@healthwaresystems.com"
        
        # Add and commit changes
        git add .
        git diff --cached --name-only  # Check what files are staged
        git commit -m "Incremented version to ${{ env.new_version }}" || echo "No changes to commit"
        
        # Push changes to main branch
        git push origin main
